# Generated by Django 5.2.4 on 2025-07-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("session_id", models.CharField(max_length=100)),
                ("initial_message", models.TextField()),
                ("conversation_history", models.JSONField(default=list)),
                ("clinical_scores", models.JSONField(default=dict)),
                (
                    "classified_category",
                    models.CharField(
                        choices=[
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("trauma", "Trauma"),
                            ("lifestyle", "Lifestyle Coaching"),
                            ("crisis", "Crisis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("crisis", "Crisis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("routing_reasoning", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_agent", models.CharField(max_length=50)),
                ("secondary_agents", models.JSONField(default=list)),
                ("urgency_level", models.CharField(max_length=20)),
                ("immediate_actions", models.JSONField(default=list)),
                ("treatment_plan", models.JSONField(default=dict)),
                ("self_help_tools", models.JSONField(default=list)),
                (
                    "crisis_resources",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("requires_immediate_attention", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_decisions",
                        to="routing_agent.userconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
